; -*- mode: emacs-lisp -*-
(source gnu)
(source melpa)
(source marmalade)

(depends-on "color-theme")
(depends-on "cask")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "idle-highlight-mode")

(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
(depends-on "rubocop")
(depends-on "color-theme-solarized")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "color-theme")
(depends-on "coffee-mode")
(depends-on "lua-mode")
(depends-on "clojure-mode")
(depends-on "ansible")

(depends-on "clojure-env")
(depends-on "slime-clj")
(depends-on "gitignore-mode")
(depends-on "web-mode")
(depends-on "go-mode")
(depends-on "handlebars-mode")
(depends-on "markdown-mode")
(depends-on "ruby-mode")
(depends-on "js2-mode")
(depends-on "yaml-mode")
(depends-on "json-mode")
(depends-on "python-mode")
(depends-on "rainbow-delimiters")
(depends-on "scss-mode")
(depends-on "projectile")
(depends-on "helm")
(depends-on "helm-projectile")
(depends-on "flycheck")
(depends-on "move-text")
(depends-on "undo-tree")
