(progn
  (require 'package)
  (add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/") t)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (setq package-check-signature nil)
  (when (string-match-p "26" (emacs-version))
    (package-initialize))
  (dolist (package '(use-package))
    (unless (package-installed-p package)
      (package-refresh-contents)
      (package-install package))))
