(progn
  (require 'package)
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")
               t)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/")
               t)
  (setq package-check-signature nil)
  (package-initialize)
  (package-refresh-contents)
  (dolist (package '(use-package))
   (unless (package-installed-p package)
       (package-install package))))
