* This is the config dir for all the things

.files, Emacs config and utility scripts and such.

Everything ships as part of ~.emacs.d~ directory because it's 🆗

** Eighty Megs And Constantly Surprising  🎩

   My emacs and $HOME setup. Focused on:

- Clojure (read below)
- Shell scripting in Bash
- Ops stuff (Ansible, Terraform etc)
- Occasionally;
  - Ruby
  - Javascript/Typescript/React
  - Scheme
  - Common Lisp
  - Python

** Setup

If you want to use these yourself - probably a bad idea, given that I built all of this stuff to fit _my workflow_.

1. Fork this repo
2. Clone to  ~$HOME/.emacs.d~
3. ~cd .emacs.d && make~
3. Start Emacs, ~use-package~ will take over

*** Other tools and packages

~cd ~/.emacs.d/etc && brew bundle~


** Details

- I use ~bash~, I tried ~zsh~ in the past and it was not worth the effort
- you can see my old .files here: https://github.com/lukaszkorecki/DotFiles
- Emacs config is pretty light-weight, essential packages are:
  - ivy, company
  - projectile
  - monroe and clojure-mode

*** Conventions

Most *navigation* shortcuts start with ~C-c n ...~

Most *execution* shorcuts start with ~C-x ...~

*** Clojure

I've built couple of convenient things around [[https://github.com/clojure-emacs/clojure-mode][clojure-mode]] and
 [[https://github.com/sanel/monroe][Monroe]], an nREPL client.

All functions are in [[settings/lk/clojure.el][settings/lk/clojure.el]]

*** ~lk/clojure-scratch~

Creates a scratch buffer and loads handy functions into the REPL process.
Tests can be run via ~(scratch/t)~ function, which also accepts
a regex ~(scratch/t ".*component.pg-test")~

The code which defines the ~scratch~ namespace depends on couple of things:

1. Leiningen profile which loads ~tools.namespace~, [[https://github.com/weavejester/eftest][eftest]] etc
2. Simple namespace definition, found in [[etc/scratch.clj][etc/repl.clj]]

*** ~lk/clojure-format-current-buffer~

Delegates to [[https://github.com/weavejester/cljfmt][cljfmt]] to format current buffer via *compilation-mode*

*** ~lk/clojure/check-current-buffer~

    Delegates to [[https://github.com/borkdude/clj-kondo][clj-kondo]] to check current buffer via *compilation-mode*
