* This is the config dir for all the things

.files, Emacs config and utility scripts and such.

Everything ships as part of ~.emacs.d~ directory because it's 🆗

** Eighty Megs And Constantly Surprising  🎩

   My emacs and $HOME setup. Focused on:

- Clojure
- Shell scripting in Bash
- Ops (Terraform, mostly)
- Javascript/Typescript/React


** Setup

If you want to use these yourself - probably a bad idea, given that I built all of this stuff to fit _my workflow_.

1. Fork this repo
2. Clone to  ~$HOME/.emacs.d~
3. ~cd .emacs.d && make~
3. Start Emacs, ~use-package~ will take over

*** Other tools and packages

There's a `Brewfile` provided, run `brew bundle`


** Details

Most, if not all languages I work with are setup to use Eglot for LSP and Treesitter for syntax highlighting.

My Clojure workflow leans heavily on `clojure-mode` + [[https://github.com/sanel/monroe][Monroe]] + my own REPL helpers library, [[https://github.com/lukaszkorecki/rumble][Rumble]] - it includes helpers for running tests, interacting with [[https://github.com/djblue/portal][Portal]]

For navigation and autocomplete, I use Ivy + whatever else it needs (Swiper, Company) etc.
In rare cases I need to do something in the terminal, vterm has my back.

** Other

I would be surprised if this config works for anybody else :-)
