#!/usr/bin/env bash

set -eo pipefail

name=$1
command=$2

sshKey=~/.ssh/multipass.id_rsa

if [[ "$name" == "" ]] ; then
  echo Need a name!
  multipass list
  exit 1
fi

if [[ "$name" == "work" || "$name" == "dev" ]] ; then
  echo > $name $command
else
  echo Unknown machine name: $name
  exit 1
fi


# If we don't have it - get the multipass ssh key, we will need sudo for that
if [[ ! -e $sshKey  ]] ; then
  sudo cp /var/root/Library/Application\ Support/multipassd/ssh-keys/id_rsa $sshKey
  sudo chown $USER:staff .ssh/multipass.id_rsa
fi



if [[ "$command" == "stop" ]] ; then
  multipass stop $name
  exit 0
fi

if [[ "$command" == "suspend" ]] ; then
  multipass stop $name
  exit 0
fi


# Create the machine if not there
if [[ "$(multipass list | grep $name)" == "" ]] ;then
  multipass launch \
            --cpus 4 \
            --mem 4G \
            --disk 20G \
            --name $name \
            18.04

fi

if [[ "$command" == "provision" ]] ; then
  multipass tranfser ./provision.sh work:/tmp/provision.sh
  multipass exec work -- sudo bash /tmp/provision.sh
  exit 0
fi


# start if not running
if [[ "$(multipass info $name --format json | jq -r .info.$name.state)" != "Running" ]] ; then
  multipass start $name
fi

# start shell
if [[ "$command" == "shell" ]] ; then
  multipass shell $name
  exit 0
fi


ip=$(multipass info $name --format json | jq -r .info.$name.ipv4[0])

if [[ "$command" == "tunnels" ]] ; then
  ssh ubuntu@$ip \
      -N \
      -i $sshKey \
      -A \
      -L 3000:localhost:3000 \
      -L 3001:localhost:3001 \
      -L 3005:localhost:3005 \
      -L 3034:localhost:3034 \
      -L 8025:localhost:8025 \
      -L 9100:localhost:9100 \
      -L 9630:localhost:9630
fi


if [[ "$command" == "ssh" ]] ; then
  ssh ubuntu@$ip -i $sshKey -A
fi
