Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"

  config.vm.network 'private_network', ip: '192.168.34.10'

  [ 3000, 3034].each do |port|
    config.vm.network "forwarded_port", guest: port, host: port
  end

  (9000..10000).each do |port|
    config.vm.network "forwarded_port", guest: port, host: port
  end

  (8000..8100).each do |port|
    config.vm.network "forwarded_port", guest: port, host: port
  end

  config.vm.synced_folder "./share", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = (1024*5).to_i
  end

  config.vm.provision "shell", path: './provision.sh'

end
