def vm_config(ip, extended_port_ranges)
  lambda do |config|
    config.ssh.forward_agent = true
    config.vm.box = "hashicorp/bionic64"
    config.vm.box_version = "1.0.282"

    config.vm.network 'private_network', ip: ip

    extended_port_ranges.each do |r|
      r.each do |port|
      config.vm.network "forwarded_port", guest: port, host: port
      end
    end

    config.vm.synced_folder "./share", "/vagrant"

    config.vm.provider "virtualbox" do |vb|
      vb.cpus = 4
      vb.memory = (1024*5).to_i
    end


    config.vm.provision "shell", path: './provision.sh'
  end
end

Vagrant.configure("2") do |config|
  config.vm.define "work", &(vm_config('192.168.34.10',
                                       [[3000,3034], (9000..10000), (8000..8100)]))
  config.vm.define "dev", &(vm_config('192.168.34.11',
                                      [[3000, 3034, 8025], (9000..10000)]))
end
