#!/usr/bin/env bash

# ./work stop :-)
if [[ "$1" == "stop" ]] ; then
  multipass stop work
  exit 0
fi

if [[ "$1" == "suspend" ]] ; then
  multipass stop work
  exit 0
fi


# Create the machine if not there
if [[ "$(multipass list | grep work)" == "" ]] ;then
  multipass launch \
            --cpus 4 \
            --mem 4G \
            --disk 20G \
            --name work \
            18.04

fi

# start if not running
if [[ "$(multipass list | egrep work.+Running)" == "" ]] ; then
  multipass start work
fi

# start shel
if [[ "$1" == "shell" ]] ; then
  multipass shell work
fi

# If we don't have it - get the multipass ssh key, we will need sudo for that
if [[ ! -e ~/.ssh/multipass.id_rsa  ]] ; then
  sudo cp /var/root/Library/Application\ Support/multipassd/ssh-keys/id_rsa ~/.ssh/multipass.id_rsa
  sudo chown $USER:staff .ssh/multipass.id_rsa
fi

# finally, shell in via SSH so that keys work, forward the agent and tunnel some port
ip=$( multipass list | awk '/work/ { print $3 }')

ssh ubuntu@$ip \
    -i ~/.ssh/multipass.id_rsa \
    -A \
    -L 3034:localhost:3034 \
    -L 8025:localhost:8025 \
    -L 3005:localhost:9989 \
    -L 3001:localhost:8080
