# -*- mode: sh -*-
export LANG=en_US.UTF-8
unset LC_ALL ; unset LC_LANG
unset command_not_found_handle

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

if [[ "$TERM" == "dumb" ]] ; then
    PS1="$ "
    return
fi

# disable stupid C-s / C-q stuff
stty -ixon

# Tiny wrappers around tput, used in prompt and messages
Color() {
  echo "$(tput setaf $1)"
}

ResetColor() {
  echo "$(tput sgr0)"
}

# Sort out SSH stuff
LoadSshKeys() {
  ssh-add -l 2>&1
  if [[ "$?" != "0" ]] ; then
    echo "> Reactivating ssh-agent"
    eval `ssh-agent`
  fi

  env TERM='' SSH_ASKPASS=~/.private/bin/askpass DISPLAY=:0:0 setsid ssh-add ~/.ssh/id_rsa  </dev/null
  keychain -Q ~/.ssh/id_rsa
}

if [[ "$(uname)" == "Linux" ]] ; then
  LoadSshKeys
fi


# Load key via macos keychain, also shut up about ZSH
if [[ "$(uname)" == "Darwin" ]] ; then
  ssh-add -K ~/.ssh/id_rsa
  export BASH_SILENCE_DEPRECATION_WARNING=1
fi



# custom scripts and tools
export PATH=$HOME/.emacs.d/etc/bin:$PATH
export PATH=$HOME/.emacs.d/vm:$PATH
export PATH=$HOME/.private/bin:$PATH
export PATH=$HOME/bin:$PATH
export PATH=$HOME/bin/google-cloud-sdk/bin:$PATH
export PATH=~/Dropbox/Scripts:$PATH
export PATH=./node_modules/.bin:$PATH
export PATH=/usr/local/bin:$PATH


# colors in less and ls
export LESS="-rRSM~gIsw"
export LSCOLORS="Gxfxcxdxbxegedabagacad"

# go
export PATH=$PATH:/usr/local/go/bin/
export GOPATH=~/pjs/
export PATH=$PATH:$GOPATH/bin

# clojure
export LEIN_REPL_PORT=9102
export LEIN_REPL_HHOST=0.0.0.0

# append to the history file, don't overwrite it
export HISTCONTROL=ignoreboth
export WORDCHARS=''
shopt -s histappend

# sync history between different sessions, a bit hacky, wish it worked like
# in ZSH
export HISTSIZE=90000000
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignorespace:ignoredups

# load extra shell env files only if they are readable
[[ -r ~/.private/env.sh ]] && source ~/.private/env.sh

# bash completion on OSX (needs brew install bash-completion)
if [[ $(uname) = "Darwin" ]] && [[ "$(which brew)" != "" ]]  ; then
  if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
  fi
fi

if [[ -f /usr/share/bash-completion/bash_completion  ]] ; then
  . /usr/share/bash-completion/bash_completion
fi


history() {
  _bash_history_sync
  builtin history "$@"
}

# "callback" for use after running a command
_bash_history_sync() {
  builtin history -a
  HISTFILESIZE=$HISTSIZE
  builtin history -c
  builtin history -r
}

# nice things
shopt -s checkwinsize # track terminal window resize
shopt -s extglob      # extended globbing capabilities
shopt -s cdspell      # fix minor typos when cd'ing
shopt -s cmdhist      # preserve new lines in history

# these options are only availabe in Bash4, which is
# not available in OSX
if [[ $BASH_VERSION == 4* ]] ; then
  shopt -s autocd       # type 'dir' instead 'cd dir'
  shopt -s dirspell     # correct typos when tab-completing names
  shopt -s globstar     # enable **
fi

alias grep='grep -E --color=auto'
alias egrep='grep -E --color=auto'

alias be='bundle exec '
alias gcd='cd $(git root)'

alias emacsd='emacs --daemon'
export EDITOR=emacsclient

# get branch

prompt() {
  local __branch=$(git cb)
  if [ "$__branch" = '' ] ; then
    __branch=' '
  elif [ "$__branch" != "${__branch:0:24}" ] ; then
    __branch="${__branch:0:24}…"
  fi

  local __here=$(basename $(pwd))

  echo "# $__branch - $__here : "
}
PROMPT_COMMAND='PS1=$(prompt)'
# plug-in the history hack
PROMPT_COMMAND="$PROMPT_COMMAND ; _bash_history_sync "

export HOMEBREW_NO_AUTO_UPDATE=1

# The next line updates PATH for the Google Cloud SDK.
if [ -f '~/bin/google-cloud-sdk/path.bash.inc' ]; then source '~/bin/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '~/bin/google-cloud-sdk/completion.bash.inc' ]; then source '~/bin/google-cloud-sdk/completion.bash.inc'; fi

test -e  "${HOME}/.emacs.d/etc/jabba.sh" && source "${HOME}/.emacs.d/etc/jabba.sh"
test -e  "${HOME}/.emacs.d/etc/nvm.sh" && source "${HOME}/.emacs.d/etc/nvm.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
