# -*- mode: sh -*-
export LANG=en_US.UTF-8
unset LC_ALL ; unset LC_LANG
unset command_not_found_handle

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

if [[ "$TERM" = "dumb" ]] ; then
    PS1="$ "
    return
fi

# disable stupid C-s / C-q stuff
stty -ixon

# Tiny wrappers around tput, used in prompt and messages
Color() {
  echo "$(tput setaf $1)"
}
ResetColor() {
  echo "$(tput sgr0)"
}

# if main ssh key is not loaded - warn about it!
if [[ -z  "$(ssh-add -L | grep id_rsa)" ]] ; then
  echo "!! Main private key is not loaded! !!" >&2
fi

LoadSshKeys() {
  if ssh-add -l 2>&1 | grep 'Could not open a conn' ; then
    echo "> Reactivating ssh-agent"
    eval `ssh-agent`
  fi

  echo "> Adding id_rsa key"
  ssh-add ~/.ssh/id_rsa
}

# custom scripts and tools
export PATH=$HOME/.emacs.d/etc/bin:$PATH
export PATH=$HOME/.private/bin:$PATH
export PATH=$HOME/bin:$PATH
export PATH=$HOME/bin/google-cloud-sdk/bin:$PATH
export PATH=~/Dropbox/Scripts:$PATH
export PATH=./node_modules/.bin:$PATH
export PATH=/usr/local/bin:$PATH

# colors in less and ls
export LESS="-rRSM~gIsw"
export LSCOLORS="Gxfxcxdxbxegedabagacad"

# go
export GOPATH=/Volumes/Work/go-src
export PATH=$PATH:$GOPATH/bin

# append to the history file, don't overwrite it
export HISTCONTROL=ignoreboth
export WORDCHARS=''
shopt -s histappend

shopt -s cdspell

# sync history between different sessions, a bit hacky, wish it worked like
# in ZSH
export HISTSIZE=90000000
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignorespace:ignoredups

# load extra shell env files only if they are readable
[[ -r ~/.private/env.sh ]] && source ~/.private/env.sh

# bash completion on OSX (needs brew install bash-completion)
if [[ $(uname) = "Darwin" ]] ; then
  if [ -f $(brew --prefix)/etc/bash_completion ]; then
    echo 'loadingn completion'
    . $(brew --prefix)/etc/bash_completion
  fi
fi

history() {
  _bash_history_sync
  builtin history "$@"
}

# "callback" for use after running a command
_bash_history_sync() {
  builtin history -a
  HISTFILESIZE=$HISTSIZE
  builtin history -c
  builtin history -r
}

# Vagrant VM settings
export VM_DEFAULT_MEM=6
export VM_DEFAULT_CPUS=4
export VM_STORAGE_MEM=3
export VM_STORAGE_CPUS=4

# nice things
shopt -s checkwinsize # track terminal window resize
shopt -s extglob      # extended globbing capabilities
shopt -s cdspell      # fix minor typos when cd'ing
shopt -s cmdhist      # preserve new lines in history

# these options are only availabe in Bash4, which is
# not available in OSX
if [[ $BASH_VERSION == 4* ]] ; then
  shopt -s autocd       # type 'dir' instead 'cd dir'
  shopt -s dirspell     # correct typos when tab-completing names
  shopt -s globstar     # enable **
fi

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias be='bundle exec '
alias gcd='cd $(git root)'

alias tm=' cd ; tmux '

alias emacs-cli='/Applications/Emacs.app/Contents/MacOS/Emacs -nw'
export EDITOR='/Applications/Emacs.app/Contents/MacOS/Emacs'

# get branch

prompt() {
  local __branch=$(git cb)
  if [ "$__branch" = '' ] ; then
    __branch=' '
  elif [ "$__branch" != "${__branch:0:24}" ] ; then
    __branch="${__branch:0:24}…"
  fi

  local __here=$(basename $(pwd))
  echo "# $__branch - $__here : "
}
PROMPT_COMMAND='PS1=$(prompt)'
# plug-in the history hack
PROMPT_COMMAND="$PROMPT_COMMAND ; _bash_history_sync "

export HOMEBREW_NO_AUTO_UPDATE=1

# The next line updates PATH for the Google Cloud SDK.
if [ -f '~/bin/google-cloud-sdk/path.bash.inc' ]; then source '~/bin/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '~/bin/google-cloud-sdk/completion.bash.inc' ]; then source '~/bin/google-cloud-sdk/completion.bash.inc'; fi
