# -*- mode: sh -*-
export LANG=en_US.UTF-8
unset LC_ALL ; unset LC_LANG
unset command_not_found_handle
export UNAME=$(uname)
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

if [[ "$TERM" == "dumb" ]] ; then
    PS1="$ "
    return
fi

# disable stupid C-s / C-q stuff
stty -ixon

# Tiny wrappers around tput, used in prompt and messages
Color() {
  echo "$(tput setaf $1)"
}

ResetColor() {
  echo "$(tput sgr0)"
}

# Sort out SSH stuff
LoadSshKeys() {
  ssh-add -l 2>&1
  if [[ "$?" != "0" ]] ; then
    echo "> Reactivating ssh-agent"
    eval `ssh-agent`
  fi

  env TERM='' SSH_ASKPASS=~/.private/bin/askpass DISPLAY=:0:0 setsid ssh-add ~/.ssh/id_rsa  </dev/null
  keychain -Q ~/.ssh/id_rsa
}

if [[ "$UNAME" == "Linux" ]] ; then
  LoadSshKeys
fi


# Load key via macos keychain, also shut up about ZSH
if [[ "$UNAME" == "Darwin" ]] ; then
  ssh-add -K ~/.ssh/id_rsa
  export BASH_SILENCE_DEPRECATION_WARNING=1
fi



# custom scripts and tools
export PATH=$HOME/.emacs.d/etc/bin:$PATH
export PATH=$HOME/.emacs.d/vm:$PATH
export PATH=$HOME/.private/bin:$PATH
export PATH=$HOME/bin:$PATH
export PATH=./node_modules/.bin:$PATH
export PATH=/usr/local/bin:$PATH

export PATH=$HOME/bin/yarn-v1.22.5/bin:$PATH
export PATH=/Applications/Emacs.app//Contents/MacOS/bin-x86_64-10_10:$PATH

# colors in less and ls
export LESS="-rRSM~gIsw"
export LSCOLORS="Gxfxcxdxbxegedabagacad"

# go
export PATH=$PATH:/usr/local/go/bin/
export GOPATH=~/pjs/
export PATH=$PATH:$GOPATH/bin

# clojure
export LEIN_REPL_PORT=9102
export LEIN_REPL_HHOST=0.0.0.0

# Set Java env vars based on the custom installation path
export PATH=$PATH:$HOME/bin/jdk/Contents/Home/bin
export JAVA_CMD=$HOME/bin/jdk/Contents/Home/bin/java
export JAVAHOME=$HOME/bin/jdk/Contents/Home
export JAVA_HOME=$JAVAHOME



# append to the history file, don't overwrite it
export HISTCONTROL=ignoreboth
export WORDCHARS=''
shopt -s histappend

# sync history between different sessions, a bit hacky, wish it worked like
# in ZSH
export HISTSIZE=90000000
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignorespace:ignoredups

# load extra shell env files only if they are readable
loadIfFound() {
 [[  -f "$1" ]] && source "$1" || echo "loader: $1 not found!"
}

loadIfFound "/System/Volumes/Data/Applications/Docker.app/Contents/Resources/etc/docker.bash-completion"
loadIfFound "/System/Volumes/Data/Applications/Docker.app/Contents/Resources/etc/docker-compose.bash-completion"
loadIfFound "/Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash"
loadIfFound "$HOME/.private/env.sh"

loadIfFound "$HOME/.emacs.d/etc/node.sh"


history() {
  _bash_history_sync
  builtin history "$@"
}

# "callback" for use after running a command
_bash_history_sync() {
  builtin history -a
  HISTFILESIZE=$HISTSIZE
  builtin history -c
  builtin history -r
}

# nice things
shopt -s checkwinsize # track terminal window resize
shopt -s extglob      # extended globbing capabilities
shopt -s cdspell      # fix minor typos when cd'ing
shopt -s cmdhist      # preserve new lines in history

# these options are only availabe in Bash4, which is
# not available in OSX
if [[ $BASH_VERSION == 4* ]] ; then
  shopt -s autocd       # type 'dir' instead 'cd dir'
  shopt -s dirspell     # correct typos when tab-completing names
  shopt -s globstar     # enable **
fi

alias grep='grep -E --color=auto'
alias egrep='grep -E --color=auto'

alias be='bundle exec '
alias gcd='cd $(git root)'

alias ..='cd ..'
alias ...='cd ../..'
alias .....='cd ../../..'

export EDITOR=emacsclient

# Use GUI emacs bin, but in terminal
[[  -d /Applications/Emacs.app ]] && alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs -nw'
alias emacsd='emacs --daemon'



# get branch + promp

prompt() {
  local __branch=$(git cb)
  if [ "$__branch" = '' ] ; then
    __branch=' '
  elif [ "$__branch" != "${__branch:0:24}" ] ; then
    __branch="${__branch:0:24}…"
  fi

  local __here=$(basename $(pwd))

  local sig='#'

  if [[ "$UNAME" == "Darwin" ]] ; then
    sig='%'
  fi


  echo "$sig $__branch - $__here : "
}
PROMPT_COMMAND='PS1=$(prompt)'
# plug-in the history hack
PROMPT_COMMAND="$PROMPT_COMMAND ; _bash_history_sync "

export HOMEBREW_NO_AUTO_UPDATE=1
