[tools]
node = 'lts'
java = ['temurin-11', 'temurin-21']

[settings]
idiomatic_version_file_enable_tools = ['node', 'java']

always_keep_download = false
always_keep_install = false

trusted_config_paths = [
    '~/pj', '~/ps'
]

verbose = false
http_timeout = "30s"
jobs = 4
raw = false
yes = false
