#!/usr/bin/env bash

ln -fvs ~/.emacs.d/etc/bashrc ~/.bashrc
ln -fvs ~/.emacs.d/etc/bashrc ~/.profile
ln -fvs ~/.emacs.d/etc/gitconfig ~/.gitconfig
ln -fvs ~/.emacs.d/etc/gitignore_global ~/.gitignore_global
ln -fvs ~/.emacs.d/etc/lein ~/.lein
ln -fvs ~/.emacs.d/init.el ~/.emacs
ln -fvs ~/.emacs.d/etc/tmux.conf  ~/tmux.conf
