# -*- mode: sh -*-

## custom paths
export PATH=$HOME/.emacs.d/etc/bin:$PATH

export PATH=$HOME/bin:$PATH
export PATH=./node_modules/.bin:$PATH
export PATH=/usr/local/bin:$PATH

export PATH=~/bin/node/bin:$PATH

export PATH=~/bin/google-cloud-sdk/bin:$PATH

export PATH=$PATH:$HOME/bin/jdk/Contents/Home/bin
export JAVA_CMD=$HOME/bin/jdk/Contents/Home/bin/java
export JAVAHOME=$HOME/bin/jdk/Contents/Home
export JAVA_HOME=$JAVAHOME

alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs -nw'
alias gcd='cd $(git root)'

export EDITOR=emacs

## prompt
export PROMPT="%1~ # "

# right-side prompt with git info
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
RPROMPT=\$vcs_info_msg_0_
zstyle ':vcs_info:git:*' formats '%F{240}(%b)%r%f'
zstyle ':vcs_info:*' enable git

## navigation
# make path operations work like bash (e.g. M-backspace deletes path fragments)
autoload -U select-word-style
select-word-style bash

# auto-cd
setopt AUTO_CD

## secrets and stuff
if [[ -e ~/.private/env.sh  ]] ; then
  source ~/.private/env.sh
fi

## load completions

autoload -Uz compinit && compinit
autoload _git
autoload _docker
autoload _docker-compose
